#define OK 0
#define ERRO_VERTICE_NAO_ENCONTRADO 1
#define ERRO_MEMORIA_INSUFICIENTE 2
#define ERRO_ARESTA_JA_EXISTENTE 3
#define ERRO_PESO_ARESTA_NAO_POSITIVO 4
#define ERRO_ABRIR_ARQUIVO 5
#define ERRO_CRIAR_GRAFO 6
#define ERRO_INSERCAO_CIDADE_TOUR_INVALIDA 7